In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
W = [[1, 1, 1],
     [1.5, 1.5, 1.5],
     [2, 2, 2]]

# 3x1
x = [[6], [7], [8]]
# 3x1
b = [[1], [1], [1]]

# Variable to store output
# 3x1
y = [[0], [0], [0]]

In [3]:
W_np = np.array(W)

x_np = np.array(x)

# Lets use the function "ones" to create an array of ones!
b_np = np.ones((3, 1))

# Lets now compute Wx + b using these numpy variables!
output = np.matmul(W_np, x_np) + b_np

# Print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 [[22. ]
 [32.5]
 [43. ]]
Output shape:
 (3, 1)


In [4]:
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)

In [5]:
tensor_2

tensor([[[0.7528, 0.9164, 0.2221],
         [0.3289, 0.0993, 0.0495],
         [0.8483, 0.2426, 0.0917]],

        [[0.1380, 0.1422, 0.6643],
         [0.2317, 0.0352, 0.5077],
         [0.5441, 0.2181, 0.9291]],

        [[0.3754, 0.5602, 0.4307],
         [0.3385, 0.0596, 0.3224],
         [0.2782, 0.3415, 0.6057]]])

In [6]:
tensor = torch.rand(2,3,1,4)
print("Our Tensor:\n",tensor)

Our Tensor:
 tensor([[[[0.2626, 0.2877, 0.0619, 0.4492]],

         [[0.6109, 0.6961, 0.9484, 0.8915]],

         [[0.1187, 0.6545, 0.2802, 0.0044]]],


        [[[0.7070, 0.5193, 0.8084, 0.0733]],

         [[0.7445, 0.6011, 0.1574, 0.1687]],

         [[0.1358, 0.4447, 0.0494, 0.5804]]]])


In [7]:
tensor[0,2]

tensor([[0.1187, 0.6545, 0.2802, 0.0044]])

In [9]:
# Select all elements of dim0
# The 2nd element of dim1
# The 1st element of dim2
# The 3rd element of dim3
print("\nIndexed elements:\n",tensor[:, 1, 0, 2])


Indexed elements:
 tensor([0.9484, 0.1574])


In [12]:
print("\nIndexed elements:\n",tensor[:, 1,0])


Indexed elements:
 tensor([[0.6109, 0.6961, 0.9484, 0.8915],
        [0.7445, 0.6011, 0.1574, 0.1687]])


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('logistic.csv')
df.Y = df.Y.map({'M':'0', 'B':'1'})
df.Y = df.Y.astype(float)
df.head()

Y     X1     X2      X3      X4       X5       X6      X7       X8  \
0  0.0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710   
1  0.0  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017   
2  0.0  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790   
3  0.0  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520   
4  0.0  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430   

       X9  ...    X21    X22     X23     X24     X25     X26     X27     X28  \
0  0.2419  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.1812  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.2069  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.2597  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.1809  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

      X29      X30  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 31 columns]

In [15]:
x = df.drop(columns='Y').values
y = df['Y'].values 
x = (x - x.mean())/x.std()
df.head()

Y     X1     X2      X3      X4       X5       X6      X7       X8  \
0  0.0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710   
1  0.0  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017   
2  0.0  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790   
3  0.0  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520   
4  0.0  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430   

       X9  ...    X21    X22     X23     X24     X25     X26     X27     X28  \
0  0.2419  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.1812  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.2069  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.2597  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.1809  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

      X29      X30  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 31 columns]

In [28]:
df.shape

(569, 31)

In [30]:
from sklearn.model_selection import train_test_split

class NaiveBayes:
    def fit(self, X, y):
        n_samples, n_features = X.shape
        self._classes = np.unique(y)
        n_classes = len(self._classes)

        # calculating mean, var, and prior for each class
        self._mean = np.zeros((n_classes, n_features), dtype=np.float64)
        self._var = np.zeros((n_classes, n_features), dtype=np.float64)
        self._priors = np.zeros(n_classes, dtype=np.float64)
      #  print(self._mean)

        for idx, c in enumerate(self._classes):
            X_c = X[y == c]
            self._mean[idx, :] = X_c.mean(axis=0)
            self._var[idx, :] = X_c.var(axis=0)
            self._priors[idx] = X_c.shape[0] / float(n_samples)
            #return X_c
        #return self._mean
           # return self._var[idx, :]
            print(self._priors[idx])
    

    def predict(self, X):
        #a = [x for x in X]
        #print(a)
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        posteriors = []

        # calculating  probability for each class
        for idx, c in enumerate(self._classes):
            prior = np.log(self._priors[idx])
            posterior = np.sum(np.log(self._pdf(idx, x)))
            posterior = prior + posterior
            posteriors.append(posterior)

        # returning class with highest posterior probability
        return self._classes[np.argmax(posteriors)]

    def _pdf(self, class_idx, x):
        mean = self._mean[class_idx]
        var = self._var[class_idx]
        numerator = np.exp(-((x - mean) ** 2) / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator


def accuracy(y_true, y_pred):
        accuracy = np.sum(y_true == y_pred) / len(y_true)
        return accuracy*100

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=50)

nb = NaiveBayes()
nb.fit(X_train, y_train)
predictions = nb.predict(X_test)
predictions
#print("Naive Bayes classification accuracy: ", accuracy(y_test, predictions))

0.3802197802197802
0.6197802197802198


array([1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1.])